meta_product_name: "αCentury"
meta_title: "αCentury - Fuck the world. Build your own."
meta_description: "αCentury is the #1 worldbuilding app for creative storytellers."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@alpha_century1"   # required for Twitter Cards
